"""Test-only helpers for the Review Factory.

These helpers replace the conftest auto-wrap pattern that was used prior
to RF-M3. Tests should import from this module explicitly rather than
relying on monkeypatching ``ReviewQueue.enqueue_completed_work`` at
session scope (which proved brittle to pytest conftest load order).

Quick start::

    from prismatic.review_factory.testing import (
        make_test_queue,
        enqueue_with_defaults,
    )

    def test_something():
        queue = make_test_queue()
        try:
            job_id = enqueue_with_defaults(
                queue,
                completed_work_id="agy-cw-test-1",
                task_id="GRO-TEST",
            )
            assert isinstance(job_id, str) and len(job_id) > 0
        finally:
            queue.close()

Why this module exists (RF-R2 migration context)
-----------------------------------------------
RF-R2 (``UNSTAGED_ADMISSION_CLOSED_OK``) removed the public
``ReviewQueue.enqueue_completed_work`` short-cut that tests had been
using. To preserve test ergonomics, the original conftest files
monkeypatched ``enqueue_completed_work`` at module-load time to fill in
missing ``result_packet_path`` / ``result_packet_sha256`` defaults.

That auto-wrap was brittle:
  * Two conftest files (root and inner) both installed the wrap, which
    caused infinite recursion under certain pytest load orders
    (see commit ``5e334c1``: install-once sentinel fix).
  * The fix is fragile to changes in pytest rootdir detection or to
    non-pytest consumers of the queue class.

This module is the recommended replacement: explicit, importable, no
class-level side effects.
"""

from __future__ import annotations

import hashlib
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from prismatic.review_factory.queue import ReviewQueue

# Default location for test-only bundle files. The directory is created
# lazily on first use.
_BUNDLE_ROOT = Path("/tmp/rf-test-bundles")

# Module-level cache so repeated calls with the same key reuse one
# canonical bundle. Tests that need a fresh bundle per call should pass
# a unique key (e.g. uuid) or supply their own ``result_packet_path``.
_DEFAULT_BUNDLE: dict[str, tuple[str, str]] = {}


def _safe_key(key: str) -> str:
    """Sanitize ``key`` for use as a filesystem path component."""
    return "".join(c if c.isalnum() else "_" for c in key)


def _get_default_bundle(key: str) -> tuple[str, str]:
    """Return ``(path, sha256)`` for a canonical test-only merge_candidate.json.

    The bundle content is generated by ``MergeCandidateManifest.create``
    so it passes the R2 digest-validation gate (canonical JSON, no
    unknown fields, all required fields present).

    Results are cached by ``key``; repeat calls return the same path and
    digest. The file is created lazily on first use.
    """
    if key in _DEFAULT_BUNDLE:
        return _DEFAULT_BUNDLE[key]
    from prismatic.merge_candidate_manifest import (
        MergeCandidateManifest,
        RiskTier,
    )

    bundle_dir = _BUNDLE_ROOT / _safe_key(key)
    bundle_dir.mkdir(parents=True, exist_ok=True)
    bundle_path = bundle_dir / "merge_candidate.json"
    if not bundle_path.exists():
        manifest = MergeCandidateManifest.create(
            issue_id=key,
            task_id=key,
            task_file_sha256="0" * 64,
            repository="mbgulden/prismatic-engine",
            target="main",
            base_sha="0" * 40,
            candidate_sha="0" * 40,
            changed_paths=["prismatic/core/router.py"],
            producer="test",
            preserved_candidate_location=f"/tmp/{_safe_key(key)}",
            risk_tier=RiskTier.A,
            dashboard_change=False,
            required_ci_checks=["rf-v1-verification"],
        )
        bundle_path.write_text(manifest.canonical_json() + "\n")
    digest = hashlib.sha256(bundle_path.read_bytes()).hexdigest()
    _DEFAULT_BUNDLE[key] = (str(bundle_path), digest)
    return _DEFAULT_BUNDLE[key]


def make_test_queue(db: Any = None) -> "ReviewQueue":
    """Return a ``ReviewQueue`` suitable for use in a test.

    If ``db`` is None (the common case), a fresh default
    ``ReviewFactoryDB`` is created with its own SQLite file under
    /tmp. The caller is responsible for ``queue.close()`` to release
    the database connection.

    Example::

        def test_enqueue(queue):
            queue = make_test_queue()
            try:
                ...
            finally:
                queue.close()
    """
    # Lazy import to avoid a circular dependency: queue.py imports models
    # which transitively imports from review_factory; testing.py lives
    # inside review_factory and importing queue at module top would
    # load the package twice.
    from prismatic.review_factory.queue import ReviewQueue

    return ReviewQueue(db=db)


def enqueue_with_defaults(
    queue: "ReviewQueue",
    *,
    completed_work_id: str,
    task_id: str,
    repository: str = "mbgulden/prismatic-engine",
    base_commit: str = "0" * 40,
    base_tree: str = "",
    candidate_commit: str = "0" * 40,
    candidate_tree: str = "",
    changed_paths: list[str] | None = None,
    result_packet_path: str = "",
    result_packet_sha256: str = "",
) -> str:
    """Enqueue a completed-work result with sensible test defaults.

    This is the recommended replacement for direct calls to
    ``ReviewQueue.enqueue_completed_work`` in tests. It supplies defaults
    for ``changed_paths`` (when omitted) and for
    ``result_packet_path`` / ``result_packet_sha256`` (when omitted), so
    tests can express the scenario under test without re-implementing
    bundle generation.

    Default behavior:
      * ``changed_paths`` defaults to ``["prismatic/core/router.py"]``
        when omitted or empty. Tests that need to test R2 negative
        paths (empty diff) must supply ``changed_paths=[]`` explicitly
        AND must supply ``result_packet_path`` + ``result_packet_sha256``
        explicitly.
      * ``result_packet_path`` defaults to a canonical
        ``merge_candidate.json`` under ``/tmp/rf-test-bundles/<key>/``.
      * ``result_packet_sha256`` defaults to the sha256 of that file
        (computed at first use, cached).

    Args:
        queue: A ``ReviewQueue`` (typically from ``make_test_queue()``).
        completed_work_id: Stable identifier for the completed work;
            also used as the bundle key when generating a default
            bundle.
        task_id: Linear-style ticket identifier (e.g. ``GRO-1234``).
        repository: ``owner/repo`` string.
        base_commit: SHA of the base commit (40 hex chars). Defaults to
            40 zeros for tests.
        base_tree: Tree SHA of the base; defaults to ``base_commit``.
        candidate_commit: SHA of the candidate commit.
        candidate_tree: Tree SHA of the candidate; defaults to
            ``candidate_commit``.
        changed_paths: List of file paths changed. Empty list is
            rejected by R2 (intentional, to test the gate).
        result_packet_path: Path to a real result packet file. If
            empty, a default bundle is generated.
        result_packet_sha256: SHA256 of the result packet. If empty,
            computed from the default bundle (or from the file at
            ``result_packet_path`` if that path exists locally).

    Returns:
        The ``review_job_id`` of the enqueued job (or the existing
        job id if the completed_work_id was previously enqueued —
        enqueue is idempotent).

    Raises:
        prismatic.review_factory.queue.IntakeValidationError:
            If the intake packet is invalid (empty diff, missing
            digest, synthetic path placeholder, etc.).
    """
    # Default the paths if the caller didn't (or supplied empty list).
    if not changed_paths:
        changed_paths = ["prismatic/core/router.py"]

    # Supply defaults for result_packet_path / sha256 if missing.
    if not result_packet_path or not result_packet_sha256:
        if not result_packet_path:
            bundle, digest = _get_default_bundle(completed_work_id)
            result_packet_path = bundle
        if not result_packet_sha256:
            p = Path(result_packet_path)
            if p.exists() and p.is_file():
                result_packet_sha256 = hashlib.sha256(p.read_bytes()).hexdigest()
            else:
                # Path doesn't exist locally; recompute via the cached
                # default bundle or fall back to a synthetic-but-valid
                # 64-hex digest.
                try:
                    _, digest = _get_default_bundle(completed_work_id)
                    result_packet_sha256 = digest
                except Exception:
                    result_packet_sha256 = "a" * 64

    return queue.enqueue_completed_work(
        completed_work_id=completed_work_id,
        task_id=task_id,
        repository=repository,
        base_commit=base_commit,
        base_tree=base_tree,
        candidate_commit=candidate_commit,
        candidate_tree=candidate_tree,
        changed_paths=changed_paths,
        result_packet_path=result_packet_path,
        result_packet_sha256=result_packet_sha256,
    )


__all__ = [
    "make_test_queue",
    "enqueue_with_defaults",
]
