# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import gateway_pb2 as gateway__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in gateway_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LockServiceStub:
    """── Lock Service ──────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListLocks = channel.unary_unary(
                '/prismatic.v1.LockService/ListLocks',
                request_serializer=gateway__pb2.ListLocksRequest.SerializeToString,
                response_deserializer=gateway__pb2.ListLocksResponse.FromString,
                _registered_method=True)
        self.GetLock = channel.unary_unary(
                '/prismatic.v1.LockService/GetLock',
                request_serializer=gateway__pb2.GetLockRequest.SerializeToString,
                response_deserializer=gateway__pb2.Lock.FromString,
                _registered_method=True)
        self.ListStaleLocks = channel.unary_unary(
                '/prismatic.v1.LockService/ListStaleLocks',
                request_serializer=gateway__pb2.ListStaleLocksRequest.SerializeToString,
                response_deserializer=gateway__pb2.ListStaleLocksResponse.FromString,
                _registered_method=True)


class LockServiceServicer:
    """── Lock Service ──────────────────────────────────────

    """

    def ListLocks(self, request, context):
        """List all active file locks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLock(self, request, context):
        """Get lock for a specific file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListStaleLocks(self, request, context):
        """List stale locks (heartbeat expired)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LockServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListLocks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLocks,
                    request_deserializer=gateway__pb2.ListLocksRequest.FromString,
                    response_serializer=gateway__pb2.ListLocksResponse.SerializeToString,
            ),
            'GetLock': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLock,
                    request_deserializer=gateway__pb2.GetLockRequest.FromString,
                    response_serializer=gateway__pb2.Lock.SerializeToString,
            ),
            'ListStaleLocks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListStaleLocks,
                    request_deserializer=gateway__pb2.ListStaleLocksRequest.FromString,
                    response_serializer=gateway__pb2.ListStaleLocksResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'prismatic.v1.LockService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('prismatic.v1.LockService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LockService:
    """── Lock Service ──────────────────────────────────────

    """

    @staticmethod
    def ListLocks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/prismatic.v1.LockService/ListLocks',
            gateway__pb2.ListLocksRequest.SerializeToString,
            gateway__pb2.ListLocksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/prismatic.v1.LockService/GetLock',
            gateway__pb2.GetLockRequest.SerializeToString,
            gateway__pb2.Lock.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListStaleLocks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/prismatic.v1.LockService/ListStaleLocks',
            gateway__pb2.ListStaleLocksRequest.SerializeToString,
            gateway__pb2.ListStaleLocksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RunServiceStub:
    """── Run Record Service ────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListRuns = channel.unary_unary(
                '/prismatic.v1.RunService/ListRuns',
                request_serializer=gateway__pb2.ListRunsRequest.SerializeToString,
                response_deserializer=gateway__pb2.ListRunsResponse.FromString,
                _registered_method=True)
        self.GetRun = channel.unary_unary(
                '/prismatic.v1.RunService/GetRun',
                request_serializer=gateway__pb2.GetRunRequest.SerializeToString,
                response_deserializer=gateway__pb2.RunRecord.FromString,
                _registered_method=True)
        self.CreateRun = channel.unary_unary(
                '/prismatic.v1.RunService/CreateRun',
                request_serializer=gateway__pb2.CreateRunRequest.SerializeToString,
                response_deserializer=gateway__pb2.CreateRunResponse.FromString,
                _registered_method=True)
        self.CompleteRun = channel.unary_unary(
                '/prismatic.v1.RunService/CompleteRun',
                request_serializer=gateway__pb2.CompleteRunRequest.SerializeToString,
                response_deserializer=gateway__pb2.CompleteRunResponse.FromString,
                _registered_method=True)


class RunServiceServicer:
    """── Run Record Service ────────────────────────────────

    """

    def ListRuns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RunServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListRuns': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRuns,
                    request_deserializer=gateway__pb2.ListRunsRequest.FromString,
                    response_serializer=gateway__pb2.ListRunsResponse.SerializeToString,
            ),
            'GetRun': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRun,
                    request_deserializer=gateway__pb2.GetRunRequest.FromString,
                    response_serializer=gateway__pb2.RunRecord.SerializeToString,
            ),
            'CreateRun': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRun,
                    request_deserializer=gateway__pb2.CreateRunRequest.FromString,
                    response_serializer=gateway__pb2.CreateRunResponse.SerializeToString,
            ),
            'CompleteRun': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteRun,
                    request_deserializer=gateway__pb2.CompleteRunRequest.FromString,
                    response_serializer=gateway__pb2.CompleteRunResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'prismatic.v1.RunService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('prismatic.v1.RunService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RunService:
    """── Run Record Service ────────────────────────────────

    """

    @staticmethod
    def ListRuns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/prismatic.v1.RunService/ListRuns',
            gateway__pb2.ListRunsRequest.SerializeToString,
            gateway__pb2.ListRunsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/prismatic.v1.RunService/GetRun',
            gateway__pb2.GetRunRequest.SerializeToString,
            gateway__pb2.RunRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/prismatic.v1.RunService/CreateRun',
            gateway__pb2.CreateRunRequest.SerializeToString,
            gateway__pb2.CreateRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/prismatic.v1.RunService/CompleteRun',
            gateway__pb2.CompleteRunRequest.SerializeToString,
            gateway__pb2.CompleteRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WatchdogServiceStub:
    """── Watchdog Service ──────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/prismatic.v1.WatchdogService/Health',
                request_serializer=gateway__pb2.HealthRequest.SerializeToString,
                response_deserializer=gateway__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/prismatic.v1.WatchdogService/Heartbeat',
                request_serializer=gateway__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=gateway__pb2.HeartbeatResponse.FromString,
                _registered_method=True)


class WatchdogServiceServicer:
    """── Watchdog Service ──────────────────────────────────

    """

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WatchdogServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=gateway__pb2.HealthRequest.FromString,
                    response_serializer=gateway__pb2.HealthResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=gateway__pb2.HeartbeatRequest.FromString,
                    response_serializer=gateway__pb2.HeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'prismatic.v1.WatchdogService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('prismatic.v1.WatchdogService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WatchdogService:
    """── Watchdog Service ──────────────────────────────────

    """

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/prismatic.v1.WatchdogService/Health',
            gateway__pb2.HealthRequest.SerializeToString,
            gateway__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/prismatic.v1.WatchdogService/Heartbeat',
            gateway__pb2.HeartbeatRequest.SerializeToString,
            gateway__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
