#!/usr/bin/env bash
# export-prismatic-env.sh — Set up Prismatic Engine environment variables
# Part of GRO-1494: Dual-runtime isolation
# Generated by Ned (agent:ned) — 2026-06-12
#
# Usage: source scripts/export-prismatic-env.sh
#        (or add to ~/.bashrc for persistent setup)

# ---------------------------------------------------------------------------
# PRISMATIC_HOME — Root of the Prismatic Engine ecosystem
# ---------------------------------------------------------------------------
# Default: /home/ubuntu (current VM home)
# Override: export PRISMATIC_HOME=/opt/prismatic  (for dedicated deployments)
export PRISMATIC_HOME="${PRISMATIC_HOME:-/home/ubuntu}"

# ---------------------------------------------------------------------------
# State & Configuration
# ---------------------------------------------------------------------------
export PRISMATIC_STATE_DIR="${PRISMATIC_STATE_DIR:-$PRISMATIC_HOME/.prismatic/db}"
export PRISMATIC_CONFIG_PATH="${PRISMATIC_CONFIG_PATH:-$PRISMATIC_HOME/.prismatic/config.yaml}"

# ---------------------------------------------------------------------------
# Python Environment
# ---------------------------------------------------------------------------
# Runtime PYTHONPATH — ONLY the stable symlink, NEVER the dev workspace
export PYTHONPATH="$PRISMATIC_HOME/.prismatic/active${PYTHONPATH:+:$PYTHONPATH}"

# Virtualenv activation helpers (not auto-activated — use on demand)
alias venv-stable='source "$PRISMATIC_HOME/.prismatic/venv_stable/bin/activate"'
alias venv-dev='source "$PRISMATIC_HOME/work/prismatic-engine/.venv_dev/bin/activate"'

# ---------------------------------------------------------------------------
# Network
# ---------------------------------------------------------------------------
export PRISMATIC_PORT="${PRISMATIC_PORT:-9000}"
export PRISMATIC_SANDBOX_PORT="${PRISMATIC_SANDBOX_PORT:-9001}"

# ---------------------------------------------------------------------------
# Tool Paths
# ---------------------------------------------------------------------------
export AGY_PATH="${AGY_PATH:-$PRISMATIC_HOME/.local/bin/agy}"
export JULES_PATH="${JULES_PATH:-$PRISMATIC_HOME/.local/bin/jules}"
export CODEX_PATH="${CODEX_PATH:-$PRISMATIC_HOME/.local/bin/codex}"

# ---------------------------------------------------------------------------
# Runtime Guard
# ---------------------------------------------------------------------------
# Set PRISMATIC_RUNTIME=true in daemon context so agents know they're in production
export PRISMATIC_RUNTIME="${PRISMATIC_RUNTIME:-false}"

# ---------------------------------------------------------------------------
# Promotion Pipeline
# ---------------------------------------------------------------------------
export PRISMATIC_SANDBOX_HOST="${PRISMATIC_SANDBOX_HOST:-pve1}"
export PRISMATIC_SANDBOX_TRANSPORT="${PRISMATIC_SANDBOX_TRANSPORT:-docker}"
export PRISMATIC_SANDBOX_BUILD_PATH="${PRISMATIC_SANDBOX_BUILD_PATH:-/opt/prismatic-sandbox/builds}"

# ---------------------------------------------------------------------------
# Summary (when sourced interactively)
# ---------------------------------------------------------------------------
if [ -t 0 ] && [ "${PRISMATIC_ENV_QUIET:-0}" != "1" ]; then
    echo "🔮 Prismatic Engine Environment"
    echo "   PRISMATIC_HOME:    $PRISMATIC_HOME"
    echo "   STATE_DIR:         $PRISMATIC_STATE_DIR"
    echo "   CONFIG_PATH:       $PRISMATIC_CONFIG_PATH"
    echo "   PORT:              $PRISMATIC_PORT (sandbox: $PRISMATIC_SANDBOX_PORT)"
    echo "   RUNTIME:           $PRISMATIC_RUNTIME"
    echo ""
    echo "   Aliases: venv-stable, venv-dev"
fi
