#!/usr/bin/env python3
"""
Push all Prismatic Engine reports to Google Docs.
Run this to sync reports to the shared folder.

Usage: python3 scripts/gdocs-sync.py
"""

import json
import os
import re
import time

FOLDER_ID = "1ZCPIAUIXg56iWRErRZSfI5WgfD1JcAKt"
REPORTS_DIR = os.path.join(os.path.dirname(__file__), "..", "reports")

from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build

def load_creds():
    token_env = os.environ.get("GDOCS_TOKEN")
    if not token_env:
        raise ValueError("GDOCS_TOKEN environment variable is not set.")
    try:
        return Credentials.from_authorized_user_info(json.loads(token_env))
    except Exception as e:
        raise ValueError(f"Failed to load credentials from GDOCS_TOKEN env var: {e}")

def md_to_doc_content(md_text):
    """Convert markdown to simple Docs API requests. Basic but functional."""
    requests = []
    lines = md_text.split("\n")
    text = md_text
    requests.append({"insertText": {"location": {"index": 1}, "text": text}})
    return requests

def push_report(drive, docs, filepath):
    """Push a single .md file as a Google Doc."""
    filename = os.path.basename(filepath)
    title = filename.replace(".md", "").replace("-", " ").replace("_", " ").title()
    
    with open(filepath) as f:
        content = f.read()
    
    # Create doc in folder
    doc_meta = {
        "name": title,
        "parents": [FOLDER_ID],
        "mimeType": "application/vnd.google-apps.document"
    }
    doc = drive.files().create(body=doc_meta).execute()
    doc_id = doc.get("id")
    doc_url = f"https://docs.google.com/document/d/{doc_id}"
    
    # Write content
    requests = [{"insertText": {"location": {"index": 1}, "text": content[:50000]}}]  # 50k char limit per batch
    docs.documents().batchUpdate(documentId=doc_id, body={"requests": requests}).execute()
    
    # Share with Michael
    try:
        drive.permissions().create(
            fileId=doc_id,
            body={"type": "user", "role": "writer", "emailAddress": "mbgulden@gmail.com"}
        ).execute()
    except:
        pass  # might already be shared via folder
    
    return doc_url

def main():
    creds = load_creds()
    drive = build("drive", "v3", credentials=creds)
    docs_service = build("docs", "v1", credentials=creds)
    
    # Get all .md files in reports dir
    md_files = sorted([f for f in os.listdir(REPORTS_DIR) if f.endswith(".md")])
    
    print(f"Pushing {len(md_files)} reports to Google Docs...\n")
    
    urls = {}
    for fname in md_files:
        fpath = os.path.join(REPORTS_DIR, fname)
        try:
            url = push_report(drive, docs_service, fpath)
            urls[fname] = url
            print(f"  ✅ {fname}")
            print(f"     {url}")
            time.sleep(1)  # rate limit breathing room
        except Exception as e:
            print(f"  ❌ {fname}: {e}")
    
    # Update the master index with all links
    print("\n---\nUpdating master index with report links...")
    
    index_text = "Prismatic Engine — Report Index\n\n"
    for fname, url in urls.items():
        title = fname.replace(".md", "").replace("-", " ").replace("_", " ").title()
        index_text += f"• {title}\n  {url}\n\n"
    index_text += "\n— Auto-generated by Prismatic Engine sync script"
    
    # Find the master index doc
    results = drive.files().list(
        q=f"'{FOLDER_ID}' in parents and name contains 'Master Index'",
        fields="files(id, name)"
    ).execute()
    
    index_docs = results.get("files", [])
    if index_docs:
        idx_id = index_docs[0]["id"]
        # Clear and rewrite
        docs_service.documents().batchUpdate(
            documentId=idx_id,
            body={"requests": [{"insertText": {"location": {"index": 1}, "text": index_text}}]}
        ).execute()
        print(f"Updated master index: https://docs.google.com/document/d/{idx_id}")
    
    print("\n✅ Done!")
    print(f"Folder: https://drive.google.com/drive/folders/{FOLDER_ID}")

if __name__ == "__main__":
    main()
