#!/usr/bin/env python3
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from prismatic.native_crons import export_system_crontab_lines  # noqa: E402

BEGIN = "# BEGIN PRISMATIC_NATIVE_CRONS"
END = "# END PRISMATIC_NATIVE_CRONS"


def render_block() -> str:
    lines = [BEGIN, "# Generated by scripts/install_native_crons.py. Edit PE native cron state, not this block."]
    lines.extend(export_system_crontab_lines())
    lines.append(END)
    return "\n".join(lines) + "\n"


def replace_managed_block(existing: str, block: str) -> str:
    if BEGIN in existing and END in existing:
        before, rest = existing.split(BEGIN, 1)
        _old, after = rest.split(END, 1)
        result = before.rstrip() + "\n\n" + block + after.lstrip("\n")
    else:
        result = existing.rstrip() + ("\n\n" if existing.strip() else "") + block
    return result.rstrip() + "\n"


def read_crontab() -> str:
    completed = subprocess.run(["crontab", "-l"], text=True, capture_output=True, check=False)
    if completed.returncode != 0:
        return ""
    return completed.stdout


def write_crontab(content: str) -> None:
    subprocess.run(["crontab", "-"], input=content, text=True, check=True)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Install PE-native cron definitions into user crontab")
    parser.add_argument("--dry-run", action="store_true", help="Print the resulting crontab without installing")
    args = parser.parse_args(argv)

    new_content = replace_managed_block(read_crontab(), render_block())
    if args.dry_run:
        print(new_content, end="")
        return 0
    write_crontab(new_content)
    print("Installed PE-native cron managed block")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
