#!/bin/bash
# refresh_gateway_oauth_env.sh
# Refreshes /home/ubuntu/.prismatic/env.d/linear_oauth.env with both:
#   - LINEAR_OAUTH_TOKEN (from credentials.json — minted by client_credentials)
#   - PRISMATIC_LINEAR_WEBHOOK_SECRET (from the gateway's running systemd env)
#
# Linear's webhook signing secret is NOT retrievable via the Linear API for
# security reasons (same as AWS doesn't return secret access keys). So we
# have two options when the secret drifts:
#   (a) Re-emit whatever secret the gateway is currently using — keeps things
#       running but doesn't fix HMAC drift. Used by this script.
#   (b) Rotate the secret via the Linear API (webhookUpdate mutation) AND
#       update the gateway in lockstep. See refresh_and_rotate_webhook.sh.
#
# GRO-2400 lesson: prior versions of this script only wrote
# LINEAR_OAUTH_TOKEN, so when Linear rotated the webhook signing secret, the
# gateway silently started rejecting every webhook. We now emit BOTH.
#
# systemd EnvironmentFile= re-reads on SIGHUP or restart.

set -e

CREDS=/home/ubuntu/.hermes/profiles/orchestrator/credentials.json
ENV_DIR=/home/ubuntu/.prismatic/env.d
ENV_FILE=$ENV_DIR/linear_oauth.env

mkdir -p "$ENV_DIR"

# Extract the OAuth token from credentials.json
OAUTH_TOKEN=$(python3 -c "
import json, sys
try:
    c = json.load(open('$CREDS'))
    print(c['credentials']['LINEAR_OAUTH_TOKEN']['value'])
except Exception as e:
    print(f'ERROR: {e}', file=sys.stderr)
    sys.exit(1)
")

# Extract the webhook secret from the currently-running gateway service.
# This is the canonical source — Linear doesn't expose secrets via API,
# so we read what's actually in use. If the gateway is down, fall back
# to the env file's existing value (no-op for the secret).
WEBHOOK_SECRET=$(systemctl show prismatic-gateway.service -p Environment 2>/dev/null \
    | tr ' ' '\n' \
    | grep '^PRISMATIC_LINEAR_WEBHOOK_SECRET=' \
    | head -1 \
    | cut -d= -f2-)

# Fallback: if gateway is down or systemd query fails, read existing env file
if [ -z "$WEBHOOK_SECRET" ] && [ -f "$ENV_FILE" ]; then
    WEBHOOK_SECRET=$(grep '^PRISMATIC_LINEAR_WEBHOOK_SECRET=' "$ENV_FILE" | head -1 | cut -d= -f2-)
fi

# Fallback: if nothing else, check systemd EnvironmentFile directly
if [ -z "$WEBHOOK_SECRET" ]; then
    WEBHOOK_SECRET=$(grep '^PRISMATIC_LINEAR_WEBHOOK_SECRET=' \
        /home/ubuntu/.prismatic/env.d/linear_oauth.env 2>/dev/null | head -1 | cut -d= -f2-)
fi

# Write atomically (write to tmp, mv into place so systemd never sees partial file)
TMPFILE=$(mktemp ${ENV_DIR}/.linear_oauth.env.XXXXXX)
{
    echo "# Auto-generated by refresh_gateway_oauth_env.sh. Do not edit by hand."
    echo "# systemd EnvironmentFile= picks this up on next SIGHUP or restart."
    echo "# GRO-2400: PRISMATIC_LINEAR_WEBHOOK_SECRET must be in sync with Linear."
    echo "LINEAR_OAUTH_TOKEN=$OAUTH_TOKEN"
    if [ -n "$WEBHOOK_SECRET" ]; then
        echo "PRISMATIC_LINEAR_WEBHOOK_SECRET=$WEBHOOK_SECRET"
    fi
} > "$TMPFILE"
mv "$TMPFILE" "$ENV_FILE"
chmod 600 "$ENV_FILE"

# If we couldn't find a webhook secret, warn loudly. This means Linear's
# webhook signing key is unknown — likely the gateway was never configured
# or PRISMATIC_LINEAR_WEBHOOK_SECRET was rotated out-of-band.
if [ -z "$WEBHOOK_SECRET" ]; then
    echo "WARNING: PRISMATIC_LINEAR_WEBHOOK_SECRET not found anywhere." >&2
    echo "  Gateway may be running without HMAC. Check systemd unit." >&2
    echo "  Run: systemctl show prismatic-gateway.service -p Environment" >&2
fi

# Tell systemd to reload the gateway's environment (EnvironmentFile is re-read
# when the service starts; we trigger a reload-friendly restart cycle).
if sudo -n systemctl is-active --quiet prismatic-gateway.service 2>/dev/null; then
    sudo -n systemctl reload prismatic-gateway.service 2>/dev/null || \
        sudo -n systemctl restart prismatic-gateway.service
fi

echo "OK: gateway env refreshed"
echo "  token: ${OAUTH_TOKEN:0:20}..."
if [ -n "$WEBHOOK_SECRET" ]; then
    echo "  webhook_secret: ${WEBHOOK_SECRET:0:16}..."
else
    echo "  webhook_secret: <missing>"
fi
