#!/usr/bin/env bash
# setup-dual-venvs.sh — Create stable + dev virtualenvs for Prismatic dual-runtime isolation
# Part of GRO-1494: Dual-runtime isolation
# Generated by Ned (agent:ned) — 2026-06-12
#
# Usage: bash scripts/setup-dual-venvs.sh
# Prerequisites: PRISMATIC_HOME must be set in environment

set -euo pipefail

if [ -z "${PRISMATIC_HOME:-}" ]; then
    echo "ERROR: PRISMATIC_HOME is not set."
    echo "  Run: source scripts/export-prismatic-env.sh"
    echo "  Or:  export PRISMATIC_HOME=/home/ubuntu"
    exit 1
fi

echo "=== Prismatic Engine — Dual Virtualenv Setup ==="
echo "PRISMATIC_HOME: $PRISMATIC_HOME"
echo ""

# ---------------------------------------------------------------------------
# 1. Stable Virtualenv (for executing runtime daemon + agent CLI tools)
# ---------------------------------------------------------------------------
STABLE_VENV="$PRISMATIC_HOME/.prismatic/venv_stable"
echo "[1/4] Creating stable virtualenv at: $STABLE_VENV"

mkdir -p "$(dirname "$STABLE_VENV")"

if [ -d "$STABLE_VENV" ]; then
    echo "  ⚠️  venv_stable already exists. Recreating..."
    rm -rf "$STABLE_VENV"
fi

python3 -m venv "$STABLE_VENV"
source "$STABLE_VENV/bin/activate"

# Install core dependencies for the runtime
pip install --upgrade pip setuptools wheel

# Install the prismatic engine core (from the active symlink, not dev workspace)
if [ -f "$PRISMATIC_HOME/work/prismatic-engine/setup.py" ]; then
    pip install -e "$PRISMATIC_HOME/work/prismatic-engine"
elif [ -f "$PRISMATIC_HOME/work/prismatic-engine/pyproject.toml" ]; then
    pip install -e "$PRISMATIC_HOME/work/prismatic-engine"
else
    echo "  ⚠️  No setup.py or pyproject.toml found — installing dependencies manually"
    # Fallback: install from requirements if available
    if [ -f "$PRISMATIC_HOME/work/prismatic-engine/requirements.txt" ]; then
        pip install -r "$PRISMATIC_HOME/work/prismatic-engine/requirements.txt"
    fi
fi

echo "  ✅ Stable venv created"

# ---------------------------------------------------------------------------
# 2. Dev Virtualenv (for linting, compiling, testing)
# ---------------------------------------------------------------------------
DEV_VENV="$PRISMATIC_HOME/work/prismatic-engine/.venv_dev"
echo ""
echo "[2/4] Creating dev virtualenv at: $DEV_VENV"

if [ -d "$DEV_VENV" ]; then
    echo "  ⚠️  venv_dev already exists. Recreating..."
    rm -rf "$DEV_VENV"
fi

python3 -m venv "$DEV_VENV"
source "$DEV_VENV/bin/activate"

pip install --upgrade pip setuptools wheel

# Install dev dependencies
if [ -f "$PRISMATIC_HOME/work/prismatic-engine/requirements-dev.txt" ]; then
    pip install -r "$PRISMATIC_HOME/work/prismatic-engine/requirements-dev.txt"
fi

if [ -f "$PRISMATIC_HOME/work/prismatic-engine/requirements.txt" ]; then
    pip install -r "$PRISMATIC_HOME/work/prismatic-engine/requirements.txt"
fi

echo "  ✅ Dev venv created"

# ---------------------------------------------------------------------------
# 3. Create directory structure
# ---------------------------------------------------------------------------
echo ""
echo "[3/4] Creating directory structure"

mkdir -p "$PRISMATIC_HOME/.prismatic/db"
mkdir -p "$PRISMATIC_HOME/.prismatic/sandbox"
mkdir -p "$PRISMATIC_HOME/.antigravity/contracts"

echo "  ✅ Directories created"

# ---------------------------------------------------------------------------
# 4. Summary
# ---------------------------------------------------------------------------
echo ""
echo "[4/4] Done! Summary:"
echo ""
echo "  Stable venv:  $STABLE_VENV"
echo "  Dev venv:     $DEV_VENV"
echo "  State DB:     $PRISMATIC_HOME/.prismatic/db"
echo "  Lock file:    $PRISMATIC_HOME/.antigravity/swarm_locks.json"
echo "  Contracts:    $PRISMATIC_HOME/.antigravity/contracts"
echo ""
echo "To use stable venv:  source $STABLE_VENV/bin/activate"
echo "To use dev venv:     source $DEV_VENV/bin/activate"
echo ""
echo "⚠️  NEXT: Copy config.yaml template to $PRISMATIC_HOME/.prismatic/config.yaml"
echo "    cp specs/config.yaml.template \$PRISMATIC_HOME/.prismatic/config.yaml"
